# Generated by Django 5.0.4 on 2024-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_status',
            field=models.IntegerField(choices=[(1, 'SIGNUP_COMPLETED'), (2, 'OTP_VERIFIED'), (3, 'ACCOUNT_CREATED')], default=0),
        ),
    ]
