# Generated by Django 5.0.4 on 2024-04-24 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0002_usermodel_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.IntegerField(choices=[(1, 'TESTING'), (2, 'FILE SUMMARIZATION'), (3, 'NOTE TAKING'), (4, 'RESEARCH'), (5, 'ASSIGNMENT SOLUTIONS'), (6, 'FILE TYPE CONVERSION'), (7, 'PRESENTATIONS'), (8, 'ARTICLES')], default=0)),
                ('sub_category', models.IntegerField(choices=[(1, 'QUESTIONS WITH OPTIONS'), (2, 'FLASH CARDS'), (3, 'ABILITIES'), (4, 'ACHIEVEMENTS'), (5, 'UPLOAD FILES OR BOOKS')], default=0)),
                ('result', models.JSONField(default=[])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
