# Generated by Django 4.2.11 on 2024-04-25 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0004_alter_categorymodel_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
