# Generated by Django 4.2.11 on 2024-04-25 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0006_categorymodel_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
