# Generated by Django 4.2.11 on 2024-04-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0007_usermodel_phone_no_alter_categorymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmediamodel',
            name='media_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadmediamodel',
            name='media_size',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadmediamodel',
            name='media_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_status',
            field=models.IntegerField(choices=[(1, 'SIGNUP_COMPLETED'), (2, 'OTP_VERIFIED')], default=0),
        ),
    ]
