# Generated by Django 4.2.11 on 2024-05-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0010_abilitymodel_achievementmodel_subjectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementmodel',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='whizzo_app.subjectmodel'),
        ),
        migrations.AlterModelTable(
            name='abilitymodel',
            table='Ability',
        ),
        migrations.AlterModelTable(
            name='achievementmodel',
            table='Acheivement',
        ),
        migrations.AlterModelTable(
            name='subjectmodel',
            table='Subject',
        ),
    ]
