# Generated by Django 4.2.11 on 2024-05-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0014_alter_achievementmodel_answer_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='subject_detail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
