# Generated by Django 4.2.11 on 2024-05-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0019_modulemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whizzo_app.modulemodel'),
        ),
    ]
