# Generated by Django 4.2.11 on 2024-05-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0020_permissionmodel_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionmodel',
            name='role',
        ),
    ]
