# Generated by Django 4.2.11 on 2024-05-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0021_remove_permissionmodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'subscriber'), (3, 'user'), (4, 'subadmin')], default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sub_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whizzo_app.subrolemodel'),
        ),
    ]
