# Generated by Django 4.2.11 on 2024-05-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0022_usermodel_role_usermodel_sub_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Features',
            },
        ),
        migrations.CreateModel(
            name='PurposeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Purpose',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=255)),
                ('plan_type', models.IntegerField(blank=True, choices=[(1, 'basic'), (2, 'intermediate'), (3, 'advanced')], null=True)),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'user'), (3, 'subadmin')], default=0),
        ),
    ]
