# Generated by Django 4.2.11 on 2024-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0023_featuresmodel_purposemodel_subscriptionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='features',
            field=models.ManyToManyField(to='whizzo_app.featuresmodel'),
        ),
    ]
