# Generated by Django 4.2.11 on 2024-05-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0028_testimonialmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('terms_condition', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(default='', max_length=17)),
            ],
            options={
                'db_table': 'CMS',
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
