# Generated by Django 4.2.11 on 2024-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0029_cmsmodel_usermodel_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
