# Generated by Django 4.2.11 on 2024-05-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0031_alter_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonialmodel',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonialmodel',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonialmodel',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonialmodel',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonialmodel',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonialmodel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
