# Generated by Django 4.2.11 on 2024-05-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0032_remove_testimonialmodel_user_testimonialmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whizzo_app.uploadmediamodel'),
        ),
    ]
