# Generated by Django 4.2.11 on 2024-05-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0033_categorymodel_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialmodel',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whizzo_app.uploadmediamodel'),
        ),
    ]
