# Generated by Django 4.2.11 on 2024-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0034_testimonialmodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialmodel',
            name='country_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
