# Generated by Django 4.2.11 on 2024-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0038_assignmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'QUESTIONS WITH OPTIONS'), (2, 'FLASH CARDS'), (3, 'ABILITIES'), (4, 'ACHIEVEMENTS'), (5, 'UPLOAD FILES OR BOOKS'), (6, 'NEW NOTE'), (7, 'WRITE ABOUT ME'), (8, 'NEW RESEARCH'), (9, 'UPLOAD REFERENCE')], default=0),
        ),
        migrations.AlterField(
            model_name='filesumarizationmodel',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'QUESTIONS WITH OPTIONS'), (2, 'FLASH CARDS'), (3, 'ABILITIES'), (4, 'ACHIEVEMENTS'), (5, 'UPLOAD FILES OR BOOKS'), (6, 'NEW NOTE'), (7, 'WRITE ABOUT ME'), (8, 'NEW RESEARCH'), (9, 'UPLOAD REFERENCE')], default=0),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'QUESTIONS WITH OPTIONS'), (2, 'FLASH CARDS'), (3, 'ABILITIES'), (4, 'ACHIEVEMENTS'), (5, 'UPLOAD FILES OR BOOKS'), (6, 'NEW NOTE'), (7, 'WRITE ABOUT ME'), (8, 'NEW RESEARCH'), (9, 'UPLOAD REFERENCE')], default=0),
        ),
    ]
