# Generated by Django 4.2.11 on 2024-05-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0039_alter_categorymodel_sub_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseaerchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('tone_of_voice', models.IntegerField(choices=[(1, 'FORMAL'), (2, 'INFORMATIVE'), (3, 'NARATIVE'), (4, 'OBJECTIVE'), (5, 'ANALYTICAL'), (6, 'PERSUASIVE'), (7, 'CASUAL'), (8, 'DESCRITIVE')], default=1)),
                ('specify_reference', models.IntegerField(choices=[(1, 'QUESTIONS WITH OPTIONS'), (2, 'FLASH CARDS'), (3, 'ABILITIES'), (4, 'ACHIEVEMENTS'), (5, 'UPLOAD FILES OR BOOKS'), (6, 'NEW NOTE'), (7, 'WRITE ABOUT ME'), (8, 'NEW RESEARCH'), (9, 'UPLOAD REFERENCE')], default=1)),
                ('is_reduce_citation', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_category', models.IntegerField(choices=[(1, 'QUESTIONS WITH OPTIONS'), (2, 'FLASH CARDS'), (3, 'ABILITIES'), (4, 'ACHIEVEMENTS'), (5, 'UPLOAD FILES OR BOOKS'), (6, 'NEW NOTE'), (7, 'WRITE ABOUT ME'), (8, 'NEW RESEARCH'), (9, 'UPLOAD REFERENCE')], default=0)),
                ('result', models.JSONField(default=list)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whizzo_app.uploadmediamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Research',
            },
        ),
    ]
