# Generated by Django 4.2.11 on 2024-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0041_alter_reseaerchmodel_specify_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='country_name',
            field=models.CharField(default='', max_length=17),
        ),
    ]
