# Generated by Django 4.2.11 on 2024-05-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0044_usermodel_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_verification',
            field=models.BooleanField(default=False),
        ),
    ]
