# Generated by Django 4.2.11 on 2024-06-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0045_usermodel_phone_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentmodel',
            name='download_file',
        ),
    ]
