# Generated by Django 4.2.11 on 2024-06-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0046_remove_assignmentmodel_download_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='download_file',
            field=models.TextField(default=None),
        ),
    ]
