# Generated by Django 4.2.11 on 2024-06-06 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0049_assignmentmodel_download_doc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('queries', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('reverted_back', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CustomerSupport',
            },
        ),
    ]
