# Generated by Django 4.2.11 on 2024-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0050_customersupportmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('notification_type', models.IntegerField(choices=[(1, 'push notification'), (2, 'email')], default=1)),
                ('notification_for', models.IntegerField(choices=[(1, 'all'), (2, 'user'), (3, 'subadmin')], default=1)),
            ],
            options={
                'db_table': 'Notification_Detail',
            },
        ),
    ]
