# Generated by Django 4.2.11 on 2024-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0052_filesumarizationmodel_download_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesumarizationmodel',
            name='download_highlighted_file',
            field=models.TextField(default=''),
        ),
    ]
