# Generated by Django 4.2.11 on 2024-06-11 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0053_filesumarizationmodel_download_highlighted_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConversationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sub_category', models.IntegerField(choices=[(1, 'QUESTIONS WITH OPTIONS'), (2, 'FLASH CARDS'), (3, 'ABILITIES'), (4, 'ACHIEVEMENTS'), (5, 'UPLOAD FILES OR BOOKS'), (6, 'NEW NOTE'), (7, 'WRITE ABOUT ME'), (8, 'NEW RESEARCH'), (9, 'UPLOAD REFERENCE'), (10, 'PDF TO WORD'), (11, 'WORD TO PDF'), (12, 'PDF TO JPEG'), (13, 'JPEG TO PDF'), (14, 'PDF TO EXCEL'), (15, 'EXCEL TO PDF'), (16, 'PDF TO PPT'), (17, 'PPT TO PDF')], default=0)),
                ('converted_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whizzo_app.uploadmediamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FileConversation',
            },
        ),
    ]
