# Generated by Django 4.2.11 on 2024-06-12 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0054_fileconversationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileconversationmodel',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
