# Generated by Django 4.2.11 on 2024-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0056_alter_subscriptionmodel_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
