# Generated by Django 4.2.11 on 2024-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0058_filesumarizationmodel_arabic_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='download_doc_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='download_file',
            field=models.TextField(default=''),
        ),
    ]
