# Generated by Django 4.2.11 on 2024-06-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0059_categorymodel_download_doc_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
