# Generated by Django 4.2.11 on 2024-06-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0060_categorymodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='title',
            new_name='topic',
        ),
    ]
