# Generated by Django 4.2.11 on 2024-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0061_rename_title_categorymodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='reference',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='tone',
            field=models.TextField(default=''),
        ),
    ]
