# Generated by Django 4.2.11 on 2024-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0063_categorymodel_research_file_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
