# Generated by Django 4.2.11 on 2024-06-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0064_categorymodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='research_type',
            field=models.IntegerField(default=1),
        ),
    ]
