# Generated by Django 4.2.11 on 2024-06-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0066_categorymodel_reduces_citations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='reduces_citations',
            new_name='reduced_citations',
        ),
    ]
