# Generated by Django 4.2.11 on 2024-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whizzo_app", "0067_rename_reduces_citations_categorymodel_reduced_citations"),
    ]

    operations = [
        migrations.AddField(
            model_name="abilitymodel",
            name="is_arabic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="achievementmodel",
            name="is_arabic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cmsmodel",
            name="about_us_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cmsmodel",
            name="privacy_policy_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cmsmodel",
            name="terms_condition_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationmodel",
            name="message_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationmodel",
            name="title_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="purposemodel",
            name="detail_ar",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="purposemodel",
            name="name_ar",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testimonialmodel",
            name="first_name_ar",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testimonialmodel",
            name="last_name_ar",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testimonialmodel",
            name="message_ar",
            field=models.CharField(default="", max_length=255),
        ),
    ]
