# Generated by Django 4.2.11 on 2024-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0068_abilitymodel_is_arabic_achievementmodel_is_arabic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='all_topics',
            field=models.JSONField(default=list),
        ),
    ]
