# Generated by Django 4.2.11 on 2024-06-27 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0069_categorymodel_all_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('topic', models.TextField(default='')),
                ('language', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('pov', models.CharField(default='', max_length=100)),
                ('words', models.IntegerField(default=0)),
                ('tone', models.CharField(default='', max_length=100)),
                ('all_topics', models.JSONField(default=list)),
                ('result', models.JSONField(default=list)),
                ('download_file', models.TextField(default='')),
                ('download_doc_file', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
