# Generated by Django 4.2.11 on 2024-07-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0070_articlemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
