# Generated by Django 4.2.11 on 2024-07-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0072_testingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportmodel',
            name='email',
            field=models.CharField(default=''),
        ),
    ]
