# Generated by Django 4.2.11 on 2024-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0074_alter_customersupportmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='notification_for',
            field=models.IntegerField(default=1),
        ),
    ]
