# Generated by Django 4.2.11 on 2024-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0075_alter_notificationmodel_notification_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingmodel',
            name='sub_category_type',
            field=models.IntegerField(default=1),
        ),
    ]
