# Generated by Django 4.2.11 on 2024-07-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0076_testingmodel_sub_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitymodel',
            name='corect_answer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
