# Generated by Django 4.2.11 on 2024-07-18 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0078_presentationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
