# Generated by Django 4.2.11 on 2024-07-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0079_presentationmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationmodel',
            name='binary_data',
        ),
    ]
