# Generated by Django 4.2.11 on 2024-07-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0080_remove_presentationmodel_binary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationmodel',
            name='binary_data',
            field=models.TextField(blank=True),
        ),
    ]
