# Generated by Django 4.2.11 on 2024-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0081_presentationmodel_binary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationmodel',
            name='template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
