# Generated by Django 4.2.11 on 2024-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0085_notetakingmodel_canvas_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetakingmodel',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notetakingmodel',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
