# Generated by Django 4.2.11 on 2024-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0086_notetakingmodel_is_duplicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetakingmodel',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='notetakingmodel',
            name='text_timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
