# Generated by Django 4.2.11 on 2024-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0087_notetakingmodel_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='binary_data',
            field=models.JSONField(default=''),
        ),
    ]
