# Generated by Django 4.2.11 on 2024-08-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0088_assignmentmodel_binary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='language',
            field=models.CharField(default='English'),
        ),
    ]
