# Generated by Django 4.2.11 on 2024-08-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0089_assignmentmodel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='binary_data',
            field=models.TextField(default=''),
        ),
    ]
