# Generated by Django 4.2.11 on 2024-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzo_app', '0092_alter_filesumarizationmodel_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
