PROFILE_STATUS_OPTIONS = [
    (1, "SIGNUP_COMPLETED"),
    (2, "OTP_VERIFIED")
]

CATEGORY_CHOICES = [
    (1, "TESTING"),
    (2, "FILE SUMMARIZATION"),
    (3, "NOTE TAKING"),
    (4, "RESEARCH"),
    (5, "ASSIGNMENT SOLUTIONS"),
    (6, "FILE TYPE CONVERSION"),
    (7, "PRESENTATIONS"),
    (8, "ARTICLES")
]

SUB_CATEGORY_CHOICES = [
    (1, "QUESTIONS WITH OPTIONS"),
    (2, "FLASH CARDS"),
    (3, "ABILITIES"),
    (4, "ACHIEVEMENTS"),
    (5, "UPLOAD FILES OR BOOKS"),

]